### ISSUE TITLE
Pool sometimes crashes when issuing commands

### ISSUE THREAD

**Issue by trueserve** [cheatoshin/xdag#13]
Version: `xdag client/server, version T13.654-T13.842. Transport module: dnet T11.231-T13.714.`
OS: Linux

When using commands on the pool, such as `stats`, sometimes the pool will crash. I have also seen this behavior on Linux miners. Sometimes it will work for over a day, other times nearly every command invocation will cause a crash.

Steps to reproduce:
- Run pool or miner
- Run `stats` or other commands in interactive session during normal execution of the server.

Expected result:
- See results of command

Actual result:
- Sometimes the pool or miner crashes and auto-restarts

Last 2 crashes related to this from xdag.log:
```
2018-01-23 01:07:15.564 [7f30e425f700:FATA]  Signal 28 delivered
2018-01-23 01:07:15.564 [7f30e425f700:FATA]  RIP=7f30e340efdb, EFL=293, ERR=0, CR2=0,
2018-01-23 01:07:15.564 [7f30e425f700:FATA]  RAX=0, RBX=7f30e36d18a0, RCX=7f30e340efdd, RDX=400, RSI=55ff0de52730, RDI=0, RBP=7f30e36ce400, RSP=7ffca35ed200,
2018-01-23 01:07:15.564 [7f30e425f700:FATA]  R8=7f30e425f700, R9=0, R10=0, R11=293, R12=d68, R13=7f30e36cd8c0, R14=7f30e36ce400, R15=7f30e36d18a0,
2018-01-23 01:07:15.604 [7f30e425f700:FATA]  ./xdag(+0xf28f) [0x55ff0dc1e28f]
2018-01-23 01:07:15.604 [7f30e425f700:FATA]  /lib64/libpthread.so.0(+0x13ae0) [0x7f30e3e40ae0]
2018-01-23 01:07:15.604 [7f30e425f700:FATA]  /lib64/libc.so.6(__read+0x2b) [0x7f30e340efdb]
2018-01-23 01:07:15.604 [7f30e425f700:FATA]  /lib64/libc.so.6(_IO_file_underflow+0x14d) [0x7f30e33a0fbd]
2018-01-23 01:07:15.604 [7f30e425f700:FATA]  /lib64/libc.so.6(_IO_default_uflow+0x42) [0x7f30e33a23d2]
2018-01-23 01:07:15.604 [7f30e425f700:FATA]  /lib64/libc.so.6(_IO_getline_info+0xbe) [0x7f30e339300e]
2018-01-23 01:07:15.604 [7f30e425f700:FATA]  /lib64/libc.so.6(fgets+0xc3) [0x7f30e3391a53]
2018-01-23 01:07:15.604 [7f30e425f700:FATA]  ./xdag(main+0x946) [0x55ff0dc15f86]
2018-01-23 01:07:15.604 [7f30e425f700:FATA]  /lib64/libc.so.6(__libc_start_main+0xf1) [0x7f30e3346521]
2018-01-23 01:07:15.604 [7f30e425f700:FATA]  ./xdag(_start+0x2a) [0x55ff0dc160da]

2018-01-23 01:47:00.265 [7f30e425f700:FATA]  Signal 28 delivered
2018-01-23 01:47:00.265 [7f30e425f700:FATA]  RIP=7f30e340efdb, EFL=293, ERR=0, CR2=0,
2018-01-23 01:47:00.265 [7f30e425f700:FATA]  RAX=0, RBX=7f30e36d18a0, RCX=7f30e340efdd, RDX=400, RSI=55ff0de52730, RDI=0, RBP=7f30e36ce400, RSP=7ffca35ed200,
2018-01-23 01:47:00.265 [7f30e425f700:FATA]  R8=7f30e425f700, R9=0, R10=0, R11=293, R12=d68, R13=7f30e36cd8c0, R14=7f30e36ce400, R15=7f30e36d18a0,
2018-01-23 01:47:00.279 [7f30e425f700:FATA]  ./xdag(+0xf28f) [0x55ff0dc1e28f]
2018-01-23 01:47:00.279 [7f30e425f700:FATA]  /lib64/libpthread.so.0(+0x13ae0) [0x7f30e3e40ae0]
2018-01-23 01:47:00.279 [7f30e425f700:FATA]  /lib64/libc.so.6(__read+0x2b) [0x7f30e340efdb]
2018-01-23 01:47:00.279 [7f30e425f700:FATA]  /lib64/libc.so.6(_IO_file_underflow+0x14d) [0x7f30e33a0fbd]
2018-01-23 01:47:00.279 [7f30e425f700:FATA]  /lib64/libc.so.6(_IO_default_uflow+0x42) [0x7f30e33a23d2]
2018-01-23 01:47:00.279 [7f30e425f700:FATA]  /lib64/libc.so.6(_IO_getline_info+0xbe) [0x7f30e339300e]
2018-01-23 01:47:00.279 [7f30e425f700:FATA]  /lib64/libc.so.6(fgets+0xc3) [0x7f30e3391a53]
2018-01-23 01:47:00.279 [7f30e425f700:FATA]  ./xdag(main+0x946) [0x55ff0dc15f86]
2018-01-23 01:47:00.279 [7f30e425f700:FATA]  /lib64/libc.so.6(__libc_start_main+0xf1) [0x7f30e3346521]
2018-01-23 01:47:00.279 [7f30e425f700:FATA]  ./xdag(_start+0x2a) [0x55ff0dc160da]
```

**Comment by cheatoshin** [comment]
Fixed in T13.847.

**Comment by trueserve** [comment]
Posting a commit hash instead of version, and which file(s) the bug was in would be helpful for reference.

**Comment by trueserve** [comment]
It doesn't look like I can reopen this bug, so I hope you get this message.

The bug is not fixed. Just crashed again when typing `state`.

```2018-01-24 02:05:57.347 [7f196b5b7700:FATA]  Signal 28 delivered
2018-01-24 02:05:57.347 [7f196b5b7700:FATA]  RIP=7f196a4f7fdb, EFL=293, ERR=0, CR2=0,
2018-01-24 02:05:57.347 [7f196b5b7700:FATA]  RAX=0, RBX=7f196a7ba8a0, RCX=7f196a4f7fdd, RDX=400, RSI=5602b10ad730, RDI=0, RBP=7f196a7b7400, RSP=7ffcb25fc3e0,
2018-01-24 02:05:57.347 [7f196b5b7700:FATA]  R8=7f196b5b7700, R9=0, R10=0, R11=293, R12=d68, R13=7f196a7b68c0, R14=7f196a7b7400, R15=7f196a7ba8a0,
2018-01-24 02:05:57.348 [7f196b5b7700:FATA]  ./xdag(+0xfa2f) [0x5602b0e70a2f]
2018-01-24 02:05:57.348 [7f196b5b7700:FATA]  /lib64/libpthread.so.0(+0x13ae0) [0x7f196b198ae0]
2018-01-24 02:05:57.348 [7f196b5b7700:FATA]  /lib64/libc.so.6(__read+0x2b) [0x7f196a4f7fdb]
2018-01-24 02:05:57.348 [7f196b5b7700:FATA]  /lib64/libc.so.6(_IO_file_underflow+0x14d) [0x7f196a489fbd]
2018-01-24 02:05:57.348 [7f196b5b7700:FATA]  /lib64/libc.so.6(_IO_default_uflow+0x42) [0x7f196a48b3d2]
2018-01-24 02:05:57.348 [7f196b5b7700:FATA]  /lib64/libc.so.6(_IO_getline_info+0xbe) [0x7f196a47c00e]
2018-01-24 02:05:57.348 [7f196b5b7700:FATA]  /lib64/libc.so.6(fgets+0xc3) [0x7f196a47aa53]
2018-01-24 02:05:57.348 [7f196b5b7700:FATA]  ./xdag(main+0x956) [0x5602b0e68056]
2018-01-24 02:05:57.348 [7f196b5b7700:FATA]  /lib64/libc.so.6(__libc_start_main+0xf1) [0x7f196a42f521]
2018-01-24 02:05:57.348 [7f196b5b7700:FATA]  ./xdag(_start+0x2a) [0x5602b0e681aa]```

Is there anything I can do to help find this?
